### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by grcancelliere** [grcancelliere/SEBC#1]

**Comment by grcancelliere** [comment]
Prepare EC2 or other instances - Created 5 Azure D3_v2 VMs (4 vCPUs 14GiB RAM) with CentOS 7.2

**Comment by grcancelliere** [comment]
System Configuration Checks - Created 1_preinstall.md

**Comment by grcancelliere** [comment]
Configure MySQL with a replica server - Installed MariaDB 5.5 with a Replica server
root password: toor
replication user password: rupw
CM databases users password: $user+pw

**Comment by grcancelliere** [comment]
CM/CDH Install Lab - Encountered problem with passwordless ssh: Exhausted available authentication methods
Caused by: java.io.IOException: unrecognised object: OPENSSH PRIVATE KEY
        at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
I've side stepped this error by modifying the configuration for sshd in order to accept passwords and RootLogin

**Comment by grcancelliere** [comment]
CM/CDH Install Lab - exited express install by mistake
I've deleted the temporary cluster and restarted the wizard

**Comment by grcancelliere** [comment]
CM/CDH Install Lab - created 3_cm_installed.png

**Comment by grcancelliere** [comment]
Optional - created 4_local_repo.png

**Comment by cfusi** [comment]
That is good!
Please do not neglect to check also the reverse lookup.
Here you can find a reference:
https://www.cloudera.com/documentation/other/reference-architecture/topics/ra_bare_metal_deployment.html#concept_aj4_g4l_f2b
