### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by grcancelliere** [grcancelliere/SEBC#2]

**Comment by grcancelliere** [comment]
Replicate to another cluster - created 0_replication.md

**Comment by grcancelliere** [comment]
Test HDFS performance - finished Terasort suite (the slowness was due to the missing YARN Gateway)

**Comment by grcancelliere** [comment]
Test HDFS Snapshots - created screenshot

**Comment by grcancelliere** [comment]
Enable HDFS HA - HA enabled

**Comment by grcancelliere** [comment]
Cloudera Manager Instance: http://grcsebcm.westeurope.cloudapp.azure.com:7180

**Comment by cfusi** [comment]
Lab is OK
