### ISSUE TITLE
Resources Labs

### ISSUE THREAD

**Issue by grcancelliere** [grcancelliere/SEBC#3]

**Comment by grcancelliere** [comment]
Doing the Math - updated considerations and spreadsheet screenshot

**Comment by grcancelliere** [comment]
Static Service Pools - updated configuration

**Comment by grcancelliere** [comment]
Tuning for YARN - added YARNtest runs

**Comment by cfusi** [comment]
Lab OK.
Please note   that the setting the number of mappers for the terasort job has no effect. It will create as many mappers  as many blocks of the input files
